version: '3.1'

networks:
  dojango:

services:

  db:
    networks:
      - dojango
    build:
      context: ./db
    environment:
      - POSTGRES_PASSWORD

  redis:
    networks:
      - dojango
    image: redis
    ports:
      - 6379:6379

  app:
    networks:
      - dojango
    build:
      context: ./app
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./app:/usr/app
    working_dir: /usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ./start-server.sh
